# Generated by Django 2.2.4 on 2019-09-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield', max_length=150)),
                ('restaurant', models.CharField(max_length=70)),
                ('restaurant_slug', models.SlugField(default='djangodbmodelsfieldscharfield', max_length=70)),
                ('type_of_item', models.CharField(max_length=10)),
                ('calories', models.IntegerField()),
                ('total_fat', models.DecimalField(decimal_places=1, max_digits=5)),
                ('sat_fat', models.DecimalField(decimal_places=1, max_digits=5)),
                ('trans_fat', models.DecimalField(decimal_places=1, max_digits=5)),
                ('cholesterol', models.DecimalField(decimal_places=1, max_digits=5)),
                ('sodium', models.DecimalField(decimal_places=1, max_digits=6)),
                ('carbs', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fiber', models.DecimalField(decimal_places=1, max_digits=5)),
                ('sugar', models.DecimalField(decimal_places=1, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=1, max_digits=5)),
                ('floz', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield', max_length=70)),
                ('logo', models.ImageField(upload_to='media/logos')),
                ('description', models.TextField()),
            ],
        ),
    ]
